name: Build and Publish Storybook to GitHub Pages

on:
    push:
        branches:
            - 'main'

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  cache: 'npm'
            - name: Clean install
              run: |
                  rm -rf node_modules
                  rm -rf package-lock.json
            - run: npm install
            - run: npm run build-storybook
            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: storybook-static
                  clean: true
