name: Build and Publish Storybook to GitHub Pages

on:
    push:
        branches:
            - 'main'

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Clean install
              run: |
                  rm -rf node_modules
                  rm -rf package-lock.json
            - run: npm install -g @angular/cli
            - run: npm install -g @storybook/cli
            - run: npm install
            - name: Deploy to GitHub Pages
              uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
              with:
                  build_command: npm run build-storybook
                  path: storybook-static
